/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Main */

#ifndef _Included_com_example_Main
#define _Included_com_example_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Main
 * Method:    printHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_Main_printHelloWorld
  (JNIEnv *, jclass);

/*
 * Class:     com_example_Main
 * Method:    getHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_Main_getHelloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
