; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.31101.0 

	TITLE	D:\hojin.ghim\ndkclass\20150601\hello.i
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Odtp
; File d:\hojin.ghim\ndkclass\20150601\hello.c
_TEXT	SEGMENT
_n$ = -4						; size = 4
_main	PROC

; 4    : int main() {

	push	ebp
	mov	ebp, esp
	push	ecx

; 5    :     int n = SQR(2);

	mov	DWORD PTR _n$[ebp], 4

; 6    : 
; 7    : 	return 0;

	xor	eax, eax

; 8    : }

	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
