/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Array */

#ifndef _Included_Array
#define _Included_Array
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Array
 * Method:    printIntArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_Array_printIntArray
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
