/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnitoast_LoginActivity_ProfileQuery */

#ifndef _Included_com_example_jnitoast_LoginActivity_ProfileQuery
#define _Included_com_example_jnitoast_LoginActivity_ProfileQuery
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_jnitoast_LoginActivity_ProfileQuery_ADDRESS
#define com_example_jnitoast_LoginActivity_ProfileQuery_ADDRESS 0L
#undef com_example_jnitoast_LoginActivity_ProfileQuery_IS_PRIMARY
#define com_example_jnitoast_LoginActivity_ProfileQuery_IS_PRIMARY 1L
#ifdef __cplusplus
}
#endif
#endif
