/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnitoast_LoginActivity_UserLoginTask */

#ifndef _Included_com_example_jnitoast_LoginActivity_UserLoginTask
#define _Included_com_example_jnitoast_LoginActivity_UserLoginTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
