/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Array */

#ifndef _Included_Array
#define _Included_Array
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Array
 * Method:    makeIntArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_Array_makeIntArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     Array
 * Method:    makeDoubleArray
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Array_makeDoubleArray
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
