/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    getCircleArea
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_Main_getCircleArea
  (JNIEnv *, jclass, jint);

/*
 * Class:     Main
 * Method:    getCirclePI
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Main_getCirclePI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
