/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lge_Hello */

#ifndef _Included_com_example_lge_Hello
#define _Included_com_example_lge_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lge_Hello
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lge_Hello_printHello
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lge_Hello
 * Method:    printWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lge_Hello_printWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
