/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Array */

#ifndef _Included_Array
#define _Included_Array
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Array
 * Method:    make2DIntArray
 * Signature: (II)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Array_make2DIntArray
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
