; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.31101.0 

	TITLE	E:\강형민강사\LGE\안드로이드 NDK\1st\20150601\hello.i
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Odtp
; File e:\강형민강사\lge\안드로이드 ndk\1st\20150601\hello.c
_TEXT	SEGMENT
_n$ = -4						; size = 4
_main	PROC

; 8    : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 9    : 	int n = SQR(2);

	mov	DWORD PTR _n$[ebp], 4

; 10   : 
; 11   : 	return 0;

	xor	eax, eax

; 12   : }

	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
